const WS="wss://ws.binaryws.com/websockets/v3";
const markets=[["1HZ10V","Volatility 10 (1s)"],["R_10","Volatility 10"],["1HZ25V","Volatility 25 (1s)"],["R_25","Volatility 25"],["1HZ50V","Volatility 50 (1s)"],["R_50","Volatility 50"],["1HZ75V","Volatility 75 (1s)"],["R_75","Volatility 75"],["1HZ100V","Volatility 100 (1s)"],["R_100","Volatility 100"],["1HZ150V","Volatility 150 (1s)"],["frxEURUSD","EUR/USD"],["frxGBPUSD","GBP/USD"],["frxUSDJPY","USD/JPY"],["frxXAUUSD","Gold (XAU/USD)"]];
const $=x=>document.getElementById(x); markets.forEach(x=>{let o=document.createElement("option");o.value=x[0];o.textContent=x[1];$("market").appendChild(o)});
let symbol="1HZ100V",tf=60,ws=null,candles=[],sub=null;
$("market").value=symbol;
document.querySelectorAll(".tf button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tf button").forEach(x=>x.classList.remove("active"));b.classList.add("active");tf=+b.dataset.tf;history()});
$("market").onchange=()=>{symbol=$("market").value;connect()};
function status(t,live=false){$("status").textContent="● "+t;$("status").style.color=live?"#32dc8a":"#f0b84c"}
function send(x){if(ws&&ws.readyState===1)ws.send(JSON.stringify(x))}
function connect(){if(ws)try{ws.close()}catch(e){};candles=[];status("Connecting");ws=new WebSocket(WS);ws.onopen=()=>{status("Live",true);history();send({ticks:symbol,subscribe:1,req_id:2})};ws.onmessage=e=>handle(JSON.parse(e.data));ws.onerror=()=>status("Error");ws.onclose=()=>{status("Disconnected");setTimeout(connect,3000)}}
function history(){send({ticks_history:symbol,end:"latest",count:250,style:"candles",granularity:tf,subscribe:0,req_id:1})}
function handle(d){if(d.msg_type==="history"&&d.candles){candles=d.candles.map(c=>({epoch:+c.epoch,open:+c.open,high:+c.high,low:+c.low,close:+c.close}));analyze()}if(d.msg_type==="tick"){let p=+d.tick.quote;$("price").textContent=d.tick.quote;sub=d.subscription?.id||sub;update(+d.tick.epoch,p);analyze()}}
function update(epoch,p){if(!candles.length)return;let bucket=Math.floor(epoch/tf)*tf,c=candles.at(-1);if(c.epoch!==bucket){candles.push({epoch:bucket,open:p,high:p,low:p,close:p});if(candles.length>300)candles.shift()}else{c.close=p;c.high=Math.max(c.high,p);c.low=Math.min(c.low,p)}}
function ema(a,n){if(a.length<n)return null;let k=2/(n+1),e=a.slice(0,n).reduce((x,y)=>x+y,0)/n;for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}return l===0?100:100-100/(1+g/l)}
function analyze(){if(candles.length<35)return;let a=candles.map(c=>c.close),f=ema(a,9),s=ema(a,21),rv=rsi(a),last=candles.at(-1),prev=candles.at(-2),prior=candles.slice(-6,-1);let trend=f>s?1:f<s?-1:0, mom=rv>55?1:rv<45?-1:0, str=last.close>Math.max(...prior.map(c=>c.high))?1:last.close<Math.min(...prior.map(c=>c.low))?-1:0;let recent=candles.slice(-20),hi=Math.max(...recent.map(c=>c.high)),lo=Math.min(...recent.map(c=>c.low));let liq=last.low<lo&&last.close>prev.close?1:last.high>hi&&last.close<prev.close?-1:0;let score=.35*trend+.25*mom+.25*str+.15*liq, sig=score>=.45?"BUY":score<=-.45?"SELL":"WAIT",conf=Math.round(50+Math.min(47,Math.abs(score)*47));$("signal").textContent=sig;$("signal").className="signal "+sig.toLowerCase();$("confidence").textContent=conf+"%";$("trend").textContent=trend>0?"Bullish":trend<0?"Bearish":"Neutral";$("momentum").textContent=rv>55?"Bullish ("+rv.toFixed(0)+")":rv<45?"Bearish ("+rv.toFixed(0)+")":"Mixed ("+rv.toFixed(0)+")";$("structure").textContent=str>0?"Break ↑":str<0?"Break ↓":"Range";$("liquidity").textContent=liq>0?"Sweep ↑":liq<0?"Sweep ↓":"Balanced";$("symbol").textContent=symbol;$("reason").textContent=sig==="BUY"?"Bullish trend and momentum are aligned. Wait for a pullback/retest before acting.":sig==="SELL"?"Bearish trend and momentum are aligned. Wait for a pullback/retest before acting.":"Conditions are mixed. Wait for stronger structure confirmation.";$("clock").textContent=new Date().toLocaleTimeString()}
connect();